# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Guiltylotus
description: Blog chia sẻ kiến thức cá nhân ^^
baseurl: /blog # the subpath of your site, e.g. /support
url: https://guiltylotus.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Chuyện của tui #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Guiltylotus
header: Chuyện của tui

meta_image: 

# Social Links
twitter_username:
facebook_page: https://www.facebook.com/minh.nguyenminh.58
github_username: guiltylotus
email: minh97.nguyenduc@gmail.com
linkedin_page:
instagram_username: 


# Navivation
nav_item_three: #
nav_item_three_link: #

nav_button: Về trang chủ
nav_button_link: https://guiltylotus.github.io/blog/

# Quote
quote_one_author: Andrew Hunt & David Hurst Thomas
quote_one_content: Much of the time, tomorrow looks a lot like today. But don’t count on it.

quote_two_author: Ralph Waldo Emerson
quote_two_content: Life is a journey, not a destination.


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
